version: "3.9"

services:
  grpc_server:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    links:
      - postgres
    ports:
      - "8080:${GRPC_PORT}"
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    ports:
        - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file:
      - .env
    command:
      - npm run migration:up