version: "2"

services:
  tracking_api:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    entrypoint: [ "npm","run","entrypoint" ]

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    env_file:
      - .env
