version: "2"
services:
  app:
    build: .
    links:
      - db
    depends_on:
      - db
      - redis
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    restart:
      on-failure
    env_file:
      - .env
    command:
      - "/init/main"
  db:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  migrate:
    image: migrate/migrate
    volumes:
      - ./schema/:/schema
    command:
      ["-path", "./schema" ,"-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable", "up" ]
    links:
      - db
    env_file:
      - .env