// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: schedule_tracking.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScheduleTrackingClient is the client API for ScheduleTracking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScheduleTrackingClient interface {
	//yes
	AddContainersOnTrack(ctx context.Context, in *AddOnTrackRequest, opts ...grpc.CallOption) (*AddOnTrackResponse, error)
	//yes
	AddBillNosOnTrack(ctx context.Context, in *AddOnTrackRequest, opts ...grpc.CallOption) (*AddOnTrackResponse, error)
	//yes
	UpdateTrackingTime(ctx context.Context, in *UpdateTrackingTimeRequest, opts ...grpc.CallOption) (*RepeatedBaseAddOnTrackResponse, error)
	//yes
	AddEmailsOnTracking(ctx context.Context, in *AddEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//yes
	DeleteEmailFromTrack(ctx context.Context, in *DeleteEmailFromTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//yes
	DeleteContainersFromTrack(ctx context.Context, in *DeleteFromTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//yes
	DeleteBillNosFromTrack(ctx context.Context, in *DeleteFromTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	//yes
	GetInfoAboutTrack(ctx context.Context, in *GetInfoAboutTrackRequest, opts ...grpc.CallOption) (*GetInfoAboutTrackResponse, error)
	//no
	GetTimeZone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTimeZoneResponse, error)
}

type scheduleTrackingClient struct {
	cc grpc.ClientConnInterface
}

func NewScheduleTrackingClient(cc grpc.ClientConnInterface) ScheduleTrackingClient {
	return &scheduleTrackingClient{cc}
}

func (c *scheduleTrackingClient) AddContainersOnTrack(ctx context.Context, in *AddOnTrackRequest, opts ...grpc.CallOption) (*AddOnTrackResponse, error) {
	out := new(AddOnTrackResponse)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/AddContainersOnTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) AddBillNosOnTrack(ctx context.Context, in *AddOnTrackRequest, opts ...grpc.CallOption) (*AddOnTrackResponse, error) {
	out := new(AddOnTrackResponse)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/AddBillNosOnTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) UpdateTrackingTime(ctx context.Context, in *UpdateTrackingTimeRequest, opts ...grpc.CallOption) (*RepeatedBaseAddOnTrackResponse, error) {
	out := new(RepeatedBaseAddOnTrackResponse)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/UpdateTrackingTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) AddEmailsOnTracking(ctx context.Context, in *AddEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/AddEmailsOnTracking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) DeleteEmailFromTrack(ctx context.Context, in *DeleteEmailFromTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/DeleteEmailFromTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) DeleteContainersFromTrack(ctx context.Context, in *DeleteFromTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/DeleteContainersFromTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) DeleteBillNosFromTrack(ctx context.Context, in *DeleteFromTrackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/DeleteBillNosFromTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) GetInfoAboutTrack(ctx context.Context, in *GetInfoAboutTrackRequest, opts ...grpc.CallOption) (*GetInfoAboutTrackResponse, error) {
	out := new(GetInfoAboutTrackResponse)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/GetInfoAboutTrack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scheduleTrackingClient) GetTimeZone(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetTimeZoneResponse, error) {
	out := new(GetTimeZoneResponse)
	err := c.cc.Invoke(ctx, "/schedule_tacking.ScheduleTracking/GetTimeZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScheduleTrackingServer is the server API for ScheduleTracking service.
// All implementations must embed UnimplementedScheduleTrackingServer
// for forward compatibility
type ScheduleTrackingServer interface {
	//yes
	AddContainersOnTrack(context.Context, *AddOnTrackRequest) (*AddOnTrackResponse, error)
	//yes
	AddBillNosOnTrack(context.Context, *AddOnTrackRequest) (*AddOnTrackResponse, error)
	//yes
	UpdateTrackingTime(context.Context, *UpdateTrackingTimeRequest) (*RepeatedBaseAddOnTrackResponse, error)
	//yes
	AddEmailsOnTracking(context.Context, *AddEmailRequest) (*emptypb.Empty, error)
	//yes
	DeleteEmailFromTrack(context.Context, *DeleteEmailFromTrackRequest) (*emptypb.Empty, error)
	//yes
	DeleteContainersFromTrack(context.Context, *DeleteFromTrackRequest) (*emptypb.Empty, error)
	//yes
	DeleteBillNosFromTrack(context.Context, *DeleteFromTrackRequest) (*emptypb.Empty, error)
	//yes
	GetInfoAboutTrack(context.Context, *GetInfoAboutTrackRequest) (*GetInfoAboutTrackResponse, error)
	//no
	GetTimeZone(context.Context, *emptypb.Empty) (*GetTimeZoneResponse, error)
	mustEmbedUnimplementedScheduleTrackingServer()
}

// UnimplementedScheduleTrackingServer must be embedded to have forward compatible implementations.
type UnimplementedScheduleTrackingServer struct {
}

func (UnimplementedScheduleTrackingServer) AddContainersOnTrack(context.Context, *AddOnTrackRequest) (*AddOnTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContainersOnTrack not implemented")
}
func (UnimplementedScheduleTrackingServer) AddBillNosOnTrack(context.Context, *AddOnTrackRequest) (*AddOnTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBillNosOnTrack not implemented")
}
func (UnimplementedScheduleTrackingServer) UpdateTrackingTime(context.Context, *UpdateTrackingTimeRequest) (*RepeatedBaseAddOnTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrackingTime not implemented")
}
func (UnimplementedScheduleTrackingServer) AddEmailsOnTracking(context.Context, *AddEmailRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEmailsOnTracking not implemented")
}
func (UnimplementedScheduleTrackingServer) DeleteEmailFromTrack(context.Context, *DeleteEmailFromTrackRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmailFromTrack not implemented")
}
func (UnimplementedScheduleTrackingServer) DeleteContainersFromTrack(context.Context, *DeleteFromTrackRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContainersFromTrack not implemented")
}
func (UnimplementedScheduleTrackingServer) DeleteBillNosFromTrack(context.Context, *DeleteFromTrackRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBillNosFromTrack not implemented")
}
func (UnimplementedScheduleTrackingServer) GetInfoAboutTrack(context.Context, *GetInfoAboutTrackRequest) (*GetInfoAboutTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfoAboutTrack not implemented")
}
func (UnimplementedScheduleTrackingServer) GetTimeZone(context.Context, *emptypb.Empty) (*GetTimeZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeZone not implemented")
}
func (UnimplementedScheduleTrackingServer) mustEmbedUnimplementedScheduleTrackingServer() {}

// UnsafeScheduleTrackingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScheduleTrackingServer will
// result in compilation errors.
type UnsafeScheduleTrackingServer interface {
	mustEmbedUnimplementedScheduleTrackingServer()
}

func RegisterScheduleTrackingServer(s grpc.ServiceRegistrar, srv ScheduleTrackingServer) {
	s.RegisterService(&ScheduleTracking_ServiceDesc, srv)
}

func _ScheduleTracking_AddContainersOnTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOnTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).AddContainersOnTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/AddContainersOnTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).AddContainersOnTrack(ctx, req.(*AddOnTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_AddBillNosOnTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOnTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).AddBillNosOnTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/AddBillNosOnTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).AddBillNosOnTrack(ctx, req.(*AddOnTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_UpdateTrackingTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrackingTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).UpdateTrackingTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/UpdateTrackingTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).UpdateTrackingTime(ctx, req.(*UpdateTrackingTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_AddEmailsOnTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).AddEmailsOnTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/AddEmailsOnTracking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).AddEmailsOnTracking(ctx, req.(*AddEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_DeleteEmailFromTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmailFromTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).DeleteEmailFromTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/DeleteEmailFromTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).DeleteEmailFromTrack(ctx, req.(*DeleteEmailFromTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_DeleteContainersFromTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFromTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).DeleteContainersFromTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/DeleteContainersFromTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).DeleteContainersFromTrack(ctx, req.(*DeleteFromTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_DeleteBillNosFromTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFromTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).DeleteBillNosFromTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/DeleteBillNosFromTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).DeleteBillNosFromTrack(ctx, req.(*DeleteFromTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_GetInfoAboutTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoAboutTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).GetInfoAboutTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/GetInfoAboutTrack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).GetInfoAboutTrack(ctx, req.(*GetInfoAboutTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScheduleTracking_GetTimeZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScheduleTrackingServer).GetTimeZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule_tacking.ScheduleTracking/GetTimeZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScheduleTrackingServer).GetTimeZone(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScheduleTracking_ServiceDesc is the grpc.ServiceDesc for ScheduleTracking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScheduleTracking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "schedule_tacking.ScheduleTracking",
	HandlerType: (*ScheduleTrackingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddContainersOnTrack",
			Handler:    _ScheduleTracking_AddContainersOnTrack_Handler,
		},
		{
			MethodName: "AddBillNosOnTrack",
			Handler:    _ScheduleTracking_AddBillNosOnTrack_Handler,
		},
		{
			MethodName: "UpdateTrackingTime",
			Handler:    _ScheduleTracking_UpdateTrackingTime_Handler,
		},
		{
			MethodName: "AddEmailsOnTracking",
			Handler:    _ScheduleTracking_AddEmailsOnTracking_Handler,
		},
		{
			MethodName: "DeleteEmailFromTrack",
			Handler:    _ScheduleTracking_DeleteEmailFromTrack_Handler,
		},
		{
			MethodName: "DeleteContainersFromTrack",
			Handler:    _ScheduleTracking_DeleteContainersFromTrack_Handler,
		},
		{
			MethodName: "DeleteBillNosFromTrack",
			Handler:    _ScheduleTracking_DeleteBillNosFromTrack_Handler,
		},
		{
			MethodName: "GetInfoAboutTrack",
			Handler:    _ScheduleTracking_GetInfoAboutTrack_Handler,
		},
		{
			MethodName: "GetTimeZone",
			Handler:    _ScheduleTracking_GetTimeZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schedule_tracking.proto",
}
