version: "3.9"
services:
  api:
    image: flyasea/fmc-tracking:latest
    environment:
      POSTGRES_USERNAME: tracking_user
      POSTGRES_PASSWORD: gic9R045AgNcmEJ4p3s9Rw==
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE_NAME: tracking_database
      REDIS_URL: redis:6379
      REDIS_TTL: 4h # in format 4h or 5m
      TWO_CAPTCHA_API_KEY: 48c471b79460e9c28dff026dce50d1ea
      SITC_SERVICE_USERNAME: flyasea
      SITC_SERVICE_PASSWORD: gV8VoDPshL1vm5Ll8gq3LQ==
      SITC_SERVICE_BASIC_AUTH: Basic cGlnOnBpZw==
      SITC_ACCESS_TOKEN: 2a6bf639-5233-4707-9930-d3cc66fb43dc
      CERT_DIR_PATH: ./
      PRODUCTION: 1
    depends_on:
      - postgres
      - redis
    volumes:
      - ./cert/:/app/cert
    ports:
      - "51372:51372"
    networks:
      - public
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - "6379:6379"
    networks:
      - public
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: tracking_user
      POSTGRES_PASSWORD: gic9R045AgNcmEJ4p3s9Rw==
      POSTGRES_DB: tracking_database
    networks:
      - public
  migrate:
    image: migrate/migrate
    volumes:
      - ./schema/:/schema
    command:
      [ "-path", "./schema" ,"-database",  "postgres://tracking_user:gic9R045AgNcmEJ4p3s9Rw==@postgres:5432/tracking_database?sslmode=disable", "up" ]
    depends_on:
      - db
    networks:
      - public
  dump_database:
    image: flyasea/postgres-dump:latest
    environment:
      POSTGRES_USER: tracking_user
      POSTGRES_PASSWORD: gic9R045AgNcmEJ4p3s9Rw==
      POSTGRES_DATABASE: tracking_database
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      S3_HOST: storage.yandexcloud.net
      S3_BUCKET: findmycargo
      S3_ACCESS_KEY: YCAJEj1AR2zVOssUEJ8mZ6NlQ
      S3_SECRET_KEY: YCNcz5sOcsEhQP5hcVNLPZUUTTyomqN5gfXkgiS9
      DUMP_TIME: 8h
      ENCRYPT_KEY: NWu+5jcnxWwDFR58hY42MA==
      PREFIX: tracking
      DUMP_NAME: tracking_dump
    networks:
      - public
networks:
  public:
    name: public
    external: true
