apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-conf
  labels:
    app: api-gateway
data:
  JWT_SECRET_KEY: "asdafasfasfasf"
  TRACKING_IP: "tracking-service"
  TRACKING_PORT: "51473"
  AUTH_IP: "user-service"
  AUTH_PORT: "3000"
