ALTER TABLE "price" DROP CONSTRAINT IF EXISTS "price_fk0";

ALTER TABLE "price" DROP CONSTRAINT IF EXISTS "price_fk1";

ALTER TABLE "price" DROP CONSTRAINT IF EXISTS "price_fk2";

ALTER TABLE "price" DROP CONSTRAINT IF EXISTS "price_fk3";

