apiVersion: v1
kind: ConfigMap
metadata:
  name: user-conf
  labels:
    app: user-api
data:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin123"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "postgresdb"
  JWT_SECRET_KEY: "asdafasfasfasf"
  DATABASE_HOST: "postgres"
  REDIS_URL: "redis:6379"
  SENDER_NAME: "findMyCargo"
  SENDER_EMAIL: "i20072004@gmail.com"
  UNISENDER_API_KEY: "<YOUR_API_KEY>"