version: "3.9"
services:
  api:
    image: flyasea/fmc-schedule-tracking:latest
    ports:
      - "8005:8005"
    networks:
      - public
    environment:
      TRACKING_GRPC_HOST: tracking_api
      TRACKING_GRPC_PORT: 51372
      USER_GRPC_HOST: user_api
      USER_GRPC_PORT: 9001
      POSTGRES_USER: schedule_tracking
      POSTGRES_PASSWORD: 7LBd1wr6YUrZmOaJINobBg==
      POSTGRES_DATABASE: schedule_tracking_db
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5434
      TZ: Asia/Vladivostok
      SENDER_EMAIL: base@mailing.findmycargo.ru
      EMAIL_PASSWORD: WguRaPfLXrbhAk2qNCbY
      EMAIL_SMTP_HOST: smtp.mail.ru
      EMAIL_SMTP_PORT: 465
      TIME_FORMAT: 2006-01-02 15:04
      CERT_DIR_PATH: ./
      PRODUCTION: 1
    volumes:
      - ./cert/:/app/cert
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:13.3
    restart: unless-stopped
    expose:
      - "5434"
    ports:
      - "5434:5434"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: schedule_tracking
      POSTGRES_PASSWORD: 7LBd1wr6YUrZmOaJINobBg==
      POSTGRES_DB: schedule_tracking_db
    command: -p 5434
    networks:
      - public
  migrate:
    image: migrate/migrate
    volumes:
      - ./schema/:/schema
    command:
      [ "-path", "./schema" ,"-database",  "postgres://schedule_tracking:7LBd1wr6YUrZmOaJINobBg==@postgres_db:5434/schedule_tracking_db?sslmode=disable", "up" ]
    depends_on:
      - postgres_db
    networks:
      - public
  dump_database:
    image: flyasea/postgres-dump:latest
    environment:
      POSTGRES_USER: schedule_tracking
      POSTGRES_PASSWORD: 7LBd1wr6YUrZmOaJINobBg==
      POSTGRES_DATABASE: schedule_tracking_db
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5434
      S3_HOST: storage.yandexcloud.net
      S3_BUCKET: findmycargo
      S3_ACCESS_KEY: YCAJEj1AR2zVOssUEJ8mZ6NlQ
      S3_SECRET_KEY: YCNcz5sOcsEhQP5hcVNLPZUUTTyomqN5gfXkgiS9
      DUMP_TIME: 8h
      ENCRYPT_KEY: NWu+5jcnxWwDFR58hY42MA==
      PREFIX: schedule_tracking
      DUMP_NAME: schedule_tracking_dump
    networks:
      - public
networks:
  public:
    name: public
    external: true