version: "3.9"
services:
  api:
    image: flyasea/fmc-schedule-tracking:latest
    ports:
      - "8005:8005"
    networks:
      - public
    environment:
      TRACKING_GRPC_HOST: tracking_api
      TRACKING_GRPC_PORT: 51372
      USER_GRPC_HOST: user_api
      USER_GRPC_PORT: 9001
      SENDER_NAME: FindMyCargo
      SENDER_EMAIL: <YOUR_SENDER_EMAIL>
      UNISENDER_API_KEY: <YOUR_UNISENDER_API_KEY>

networks:
  public:
    name: public
    external: true